project_id = "tryout-ujian-online-codex"

[api]
  port = 55431

[db]
  port = 55432
  shadow_port = 55430
  major_version = 15

[db.pooler]
  port = 55439

[studio]
  port = 55433

[inbucket]
  port = 55434

[analytics]
  enabled = false
  port = 55437
